# Generated by Django 3.0.4 on 2020-05-02 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_quiet_area', models.BooleanField(default=True)),
                ('floor', models.IntegerField(default=1)),
                ('area', models.CharField(max_length=1, null=True)),
                ('table_type', models.IntegerField(default=4)),
                ('has_power', models.BooleanField(default=False)),
                ('table_position_noisy', models.CharField(max_length=20, null=True)),
                ('table_position_quiet', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=True)),
                ('date', models.CharField(default=datetime.date(2020, 5, 2), max_length=20)),
                ('time_id', models.IntegerField(choices=[(1, '8:00-11:00'), (2, '13:00-17:00'), (3, '18:00-21:00')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account_App.UserProf')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book_App.Seat')),
            ],
            options={
                'db_table': 'reservation',
                'unique_together': {('account', 'seat', 'time_id')},
            },
        ),
    ]
