# Generated by Django 3.0.5 on 2020-04-19 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=1)),
                ('position', models.CharField(max_length=10, unique=True)),
                ('has_power', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_time', models.CharField(max_length=10)),
                ('is_delete', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account_App.User')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book_App.Seat')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
