# Generated by Django 3.0.5 on 2020-05-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account_App', '0002_userprof_delete_times'),
        ('Book_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('account', 'seat', 'time_id', 'date')},
        ),
    ]
