# Generated by Django 3.0.4 on 2020-05-02 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default='static/image/zhangzhe.jpg', upload_to='icon')),
                ('credit', models.PositiveIntegerField(default=5)),
                ('introduction', models.TextField(default='个人简介')),
                ('name', models.CharField(default='user', max_length=20)),
                ('student_number', models.CharField(max_length=12)),
                ('mailbox', models.EmailField(default='user@email.com', max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
                ('record_id', models.TextField(editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userprof',
            },
        ),
    ]
