# Generated by Django 3.0.5 on 2020-05-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprof',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
