# Generated by Django 3.0.5 on 2020-05-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_App', '0002_userprof_delete_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprof',
            name='icon',
            field=models.ImageField(default='static/image/default_icon.bmp', upload_to='icon'),
        ),
    ]
